export const START_REFRESH_TIMER = 'START_REFRESH_TIMER'
export const START_RESUME_NOTIFICATIONS_TIMER = 'START_RESUME_NOTIFICATIONS_TIMER'
export const CANCEL_REFRESH_TIMER = 'CANCEL_REFRESH_TIMER'
export const CANCEL_RESUME_NOTIFICATIONS_TIMER = 'CANCEL_RESUME_NOTIFICATIONS_TIMER'
