export const START_REFRESH_TIMER = 'START_SCHEDULER_FIXED_DELAY'
export const START_DO_NOT_DISTURB_TIMER = 'START_SCHEDULER_FOR_RESUMING_NOTIFICATIONS'
export const CANCEL_REFRESH_TIMER = 'STOP_SCHEDULER_FIXED_DELAY'
export const CANCEL_DO_NOT_DISTURB_TIMER = 'STOP_SCHEDULER_FOR_RESUMING_NOTIFICATIONS'
