export const CONSOLE_PAGE_TYPE = 'consolePage'
export const DETAIL_PAGE_TYPE = 'detailPage'
export const DIALOG_PAGE_TYPE = 'dialogPage'
export const MAIN_PAGE_TYPE = 'mainPage'
export const NO_REFRESH_TYPE = 'noRefreshPage'
