export const CONSOLE_PAGE_TYPE = 'consolePage'
export const CREATE_PAGE_TYPE = 'createPage'
export const DETAIL_PAGE_TYPE = 'detailPage'
export const LIST_PAGE_TYPE = 'listPage'
export const NO_REFRESH_TYPE = 'noRefreshPage'
export const EMPTY_VNIC_PROFILE_ID = ''
export const SETTINGS_PAGE_TYPE = 'settingsPage'
