export const SET_SSH_KEY = 'OPTIONS_DIALOG_HEADER_SET_SSH_KEY'
export const GET_SSH_KEY = 'OPTIONS_DIALOG_HEADER_GET_SSH_KEY'
export const SAVE_SSH_KEY = 'OPTIONS_DIALOG_HEADER_SAVE_SSH_KEY'
export const SET_UNLOADED = 'OPTIONS_DIALOG_HEADER_SET_UNLOADED'
