// @flow

export const CLEAN_NEW_DISK_DIALOG_SUBTREE = 'CLEAN_NEW_DISK_DIALOG_SUBTREE'
export const CREATE_DISK_FOR_VM = 'CREATE_DISK_FOR_VM'
export const SET_NEW_DISK_DIALOG_DONE = 'SET_NEW_DISK_DIALOG_DONE'
export const SET_NEW_DISK_DIALOG_ERROR_TEXT = 'SET_NEW_DISK_DIALOG_ERROR_TEXT'
export const SET_NEW_DISK_DIALOG_PROGRESS_INDICATOR = 'SET_NEW_DISK_DIALOG_PROGRESS_INDICATOR'
